# Generated by Django 5.0.4 on 2024-04-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="cni",
            field=models.CharField(
                error_messages={"unique": "This CNIE is already Exists! (ByMe)"},
                help_text="Upper or Lower cases isn't matter",
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="CNIE",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="registration",
            name="f_name",
            field=models.CharField(
                help_text="Only characters (Capitalize)", max_length=255
            ),
        ),
    ]
