# Generated by Django 5.0.4 on 2024-04-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_registration_cni_alter_registration_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "book_name",
                    models.CharField(max_length=300, verbose_name="Name of the book"),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="registration",
            options={"ordering": ["f_name", "l_name"]},
        ),
        migrations.AlterField(
            model_name="registration",
            name="cni",
            field=models.CharField(
                error_messages={"unique": "This CNIE is already Exists! (ByMe)"},
                help_text="*Upper or Lower cases isn't matter",
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="CNIE",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="f_name",
            field=models.CharField(
                help_text="*Only characters (Capitalize)", max_length=255
            ),
        ),
    ]
