# Generated by Django 5.0.4 on 2024-04-26 19:16

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_book_alter_registration_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="borrow_date",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created Date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Generated Automatically",
                verbose_name="Update Time",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
