# Generated by Django 5.0.4 on 2024-04-26 19:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_book_borrow_date_book_updated_at_alter_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="borrow_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
