# Generated by Django 5.0.4 on 2024-04-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Update Time"),
        ),
    ]
